### ISSUE TITLE
Mamiya communication protocoll used in RB/RZ DB communication 

### ISSUE THREAD

**Issue by Apotessar** [Alexey-Danilchenko/Kodak-DCS-Tools#1]
Hey Alexey
Thanks for the huge contribution. Your write is actual very useful to my current project. 
Just one quick question, do you know something about the DB communication of the older RB/RZ Mamiya? Is it the same as the communication protocol of the AF/AFD? 

The film and digital backs using a 4 wire connector. So do the Hasselblad V when shooting with the optional RB/RZ digital adapter. It seems possible to eliminate the requirement to use an external sync cable while shooting with an electric controlled shutter system. Or at least to shoot with an internal wake up signal.  

Introduction of RZ67 Pro IID (unknown year)
_Mamiya America Corp., Elmsford, N.J., USA, introduces the new RZ67 Pro IID digital camera back, offering advanced microprocessor technology for traditional film capture, while enabling direct communication of many camera functions to digital capture backs through its MSC (Mamiya Serial Communication) system._ 

From the Mamiya ZD Introduction (2007)
_Mamiya’s communication protocol MSCE (Mamiya Serial Communication for External) has optimized two-way communication between the 645AFD II and the ZD Digital Back,” says Karp, “producing an operating experience identical to using a one-piece digital  camera._

Can you tell if the communication protocol is similar, or is there a complete new set of commands and message id's like the communication with film backs?

Best regards 
Apotessar

**Comment by Alexey-Danilchenko** [comment]
Hi
Firstly - that's not an issue with things released in this project. 

To answer your question - no I have no experience with that. Simply because it has no relation to ProBacks 645 or other Kodak cameras that are subject of this project. From the description I would guess RZ uses something similar to film back protocol of Mamiya 645 (that is entirely different set of messages that could be partially reversed from the Mamiya communications code I reversed for ProBack 645). As with all work like this - you would need to hook up some logic analyzer to those 4 RZ wires and start analyzing it yourself.
