### ISSUE TITLE
kodak dcs pro back plus

### ISSUE THREAD

**Issue by liuhiasheng** [Alexey-Danilchenko/Kodak-DCS-Tools#4]
![微信图片_20231219121601](https://github.com/Alexey-Danilchenko/Kodak-DCS-Tools/assets/36306445/94f19fc7-73ac-462a-8020-76e39877bc4e)

This is the kodak dcs pro back plus camera chip, what model is it? Do you know?

**Comment by Alexey-Danilchenko** [comment]
Firstly, this is not an issue with my code - do not raise one. Then I don't pretend to be specialist on all Kodak hardware - I am not a Kodak engineer and have not developed their camera hardware. The chip on a photo is Xilinx Spartan FPGA - it was used on Proback 645 to implement communications with the various parts instead of ASIC. The board does not look like ProBack 645 one and I am not familiar with the others.
